=== folio-org/mod-circulation-storage/ramls/check-in.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Check-in operation",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique ID (generated UUID) of the check-in operation",
      "$ref": "raml-util/schemas/uuid.schema"
    },
    "occurredDateTime": {
      "type": "string",
      "description": "Date and time when the check-in occurred",
      "format": "date-time"
    },
    "itemId": {
      "type": "string",
      "description": "Id of item that has checked in",
      "$ref": "raml-util/schemas/uuid.schema"
    },
    "itemStatusPriorToCheckIn": {
      "type": "string",
      "description": "Item status prior to check-in"
    },
    "requestQueueSize": {
      "type": "integer",
      "description": "Request queue size for the item",
      "minimum": 0
    },
    "itemLocationId": {
      "type": "string",
      "description": "Location of the item in check-in time",
      "$ref": "raml-util/schemas/uuid.schema"
    },
    "servicePointId": {
      "type": "string",
      "description": "Service point where the item was checked in",
      "$ref": "raml-util/schemas/uuid.schema"
    },
    "performedByUserId": {
      "type": "string",
      "description": "Id of user that has performed check-in operation",
      "$ref": "raml-util/schemas/uuid.schema"
    },
    "inHouseUse": {
      "type": "boolean",
      "description": "Indicates whether the check-in was an in-house use",
      "default": false
    }
  },
  "additionalProperties": false,
  "required": [
    "occurredDateTime",
    "itemId",
    "servicePointId",
    "performedByUserId"
  ]
}

=== folio-org/mod-circulation-storage/ramls/examples/check-in.json
{
  "id": "513eba26-081d-4566-b0eb-c6f2c8db5aab",
  "occurredDateTime": "2020-02-12T16:17:25Z",
  "itemId": "6acb77b5-53f5-4005-b5c2-8ce9c52fb891",
  "itemStatusPriorToCheckIn": "Checked out",
  "itemLocationId": "99ea6fc9-ed59-45b7-9ae8-1f851ea20208",
  "requestQueueSize": 2,
  "servicePointId": "b0c3c66c-6738-4a61-a51e-8ef354d43e3d",
  "performedByUserId": "f9246eac-ef6f-4043-885b-0325a1e3a9eb",
  "inHouseUse": false
}
